update

diff --git a/Jenkinsfile/ansible.jenkinsfile b/Jenkinsfile/ansible.jenkinsfile
--- a/Jenkinsfile/ansible.jenkinsfile
+++ b/Jenkinsfile/ansible.jenkinsfile
@@ -1,7 +1,6 @@
 pipeline {
     agent any
-      environment {
-          // Define environment variables
+    environment {
         EXTERNAL_PORT = '8085'
         INTERNAL_PORT = '80'
         DOCKER_IMAGE = 'pisethsattya/jobquick-jenkins:1.0'
@@ -12,7 +11,7 @@ pipeline {
     }
 
     stages {
-        stage('clean workspace') {
+        stage('Clean Workspace') {
             steps {
                 cleanWs()
             }
@@ -22,83 +21,39 @@ pipeline {
                 git branch: 'main', url: 'https://github.com/SattyaPiseth/devops-engineering.git'
             }
         }
-        stage('check location pwd'){
-            steps{
-                sh'''
-                ls -lrt
-                pwd
-                ls /var/jenkins_home/workspace/ansible/test-ansible/shellscript/*
-                '''
-            }
-        }
-        stage('Check ansible vers') {
+        stage('Check Ansible Version') {
             steps {
                 script {
-                    sh '''ansible --version
+                    sh '''
+                    ansible --version
                     cd ~
-                    ansible -i ansible/hosts all -m ping
+                    ansible -i ${ANSIBLE_HOSTS} all -m ping
                     '''    
                 }
             }
         }
-
-        // stage('ansible create folder') {
-        //     steps {
-        //         script {
-        //             sh '''
-        //             ansible-playbook -i ansible/hosts.ini ansible/create-folder.yml
-        //             '''
-        //         }
-        //     }
-        // }
-
-        // stage('Check for Docker') {
-        //     steps {
-        //         script {
-        //             def dockerInstalled = sh(
-        //                 script: "docker --version",
-        //                 returnStatus: true
-        //             )
-
-        //             if (dockerInstalled == 0) {
-        //                 echo 'Docker is already installed on this node. Skipping Docker installation.'
-        //                 currentBuild.result = 'SUCCESS'
-        //             } else {
-        //                 echo 'Docker is not installed. Proceeding to installation...'
-        //             }
-        //         }
-        //     }
-        // }
-
-        stage('Install Docker') {
-            // when {
-            //     expression {
-            //         // Skip this stage if Docker is installed
-            //         return sh(script: "docker --version", returnStatus: true) != 0
-            //     }
-            // }
+        
+        stage('Check and Install Docker if Missing') {
             steps {
                 script {
-                    echo 'Running Ansible playbook to install Docker...'
-                    sh """
-                        ansible-playbook -i ${ANSIBLE_HOSTS} ${ANSIBLE_PLAYBOOK}
-                    """
+                    def dockerCheck = sh (
+                        script: '''
+                            ansible -i ${ANSIBLE_HOSTS} all -m shell -a "docker --version" | grep -q "not found" && echo "Docker Missing" || echo "Docker Found"
+                        ''',
+                        returnStatus: true
+                    )
+                    if (dockerCheck == 0) {
+                        echo 'Docker is missing on one or more hosts. Running installation...'
+                        sh '''
+                            ansible-playbook -i ${ANSIBLE_HOSTS} ansible/install_docker.yml
+                        '''
+                    } else {
+                        echo 'Docker is already installed on all hosts. Skipping installation.'
+                    }
                 }
             }
         }
-
-        // stage('Uninstall Docker') {
-        //     steps {
-        //         script {
-        //             sh """
-        //                 ansible-playbook -i ${ANSIBLE_HOSTS} ansible/uninstall_docker.yml
-        //             """
-        //         }
-        //     }
-        // }
-    
-
-
+        
         // stage('Deploy with Ansible') {
         //     steps {
         //         script {
